[package]
name = "simulator"
version = "0.1.0"
authors = ["Enrico Lovisotto <enricolovisotto@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
log = "0.4.6"
derive_builder = "0.7.0"
downcast-rs = "1.0.3"
rand = "0.6.5"
