#+STARTUP: indent
#+OPTIONS: toc:nil title:nil

#+LaTeX_CLASS: book
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage{charter}
#+LATEX_HEADER: \usepackage{svg}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage[showframe]{geometry}
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \graphicspath{{../figures/}}

#+LATEX_HEADER: \providetoggle{images_titlepage}
#+LATEX_HEADER: \settoggle{images_titlepage}{true}

#+BEGIN_COMMENT
Download all needed files for titlepage.
#+END_COMMENT

#+BEGIN_SRC bash :exports none :results none
  wget https://upload.wikimedia.org/wikipedia/it/5/53/Logo_Universit%C3%A0_Padova.svg \
       -O ../figures/logo_unipd.svg

  inkscape ../figures/logo_unipd.svg --export-pdf=../figures/logo_unipd.pdf

  wget https://upload.wikimedia.org/wikipedia/commons/1/11/RWTH_Logo.svg \
       -O ../figures/logo_rwth.svg

  inkscape ../figures/logo_rwth.svg --export-pdf=../figures/logo_rwth.pdf
#+END_SRC

#+BEGIN_EXPORT latex
\newgeometry{top=1in, bottom=1in, inner=1in, outer=1in}

\begin{titlepage}
  {\Large University of Padova}
  \vspace{5mm}

  {\Large Department of Information Engineering}

  \begin{center}
    \vspace{1cm}
    {\Large \textsl{Master degree in Telecommunication Engineering}} \\
    \vspace{1cm}
    {\scshape\huge TODO: Title}

    \iftoggle{images_titlepage}{
      \vspace{1cm}
      \begin{figure}[h]
        \centering
        \includegraphics[height=5cm]{logo_unipd.pdf}
        \vspace{1cm} \\
        \includegraphics[height=2cm]{logo_rwth.pdf}
        \vspace{1cm}
      \end{figure}
    }

  \end{center}

  \vfill
  \hspace{0.5cm}%
  \renewcommand{\arraystretch}{2.5}
  \begin{tabular}{lr}
    \large \textsl{Author}               & \hspace{5mm} \large Enrico Lovisotto      \\
    \large \textsl{Internal supervisor}  & \hspace{5mm} \large Prof. Andrea Zanella  \\
    \large \textsl{External supervisors} & \hspace{5mm} \large Prof. Petri Mähönen  \\
                                         & \hspace{5mm} \large Dr. Ljiljana Simić   \\
  \end{tabular}
  \vspace{1cm}

  \hfill{\large February 6, 2019} \vspace{3mm}

  \hfill{\Large Academic year 2018-2019 \par}
\end{titlepage}

\restoregeometry
#+END_EXPORT

* Introduction
  #+BEGIN_COMMENT
  + background: what are we talking about?
  - SDN => self-optimizing networks
  - flow balancing (TBF)
  - routing adaptation
  #+END_COMMENT

  #+BEGIN_COMMENT
  + what they do now?
  - summary of state of the art, /basically/
  #+END_COMMENT

  #+BEGIN_COMMENT
  + shortcomings in current knowledge / solutions
  - limits of SDN over traditional networks: lack of negative results
  - use of abstract topologies ~> this one is obtained through optimization process
  #+END_COMMENT

  #+BEGIN_COMMENT
  + what are we gonna prove?
  - 99% if the networks are very simple, meant to be more flow aggregators and less clever routers
  - SDN are not inherently good: /probably/ traditional solutions are good in 99% of the networks
  - SDN are relevant when the complexity of the network grows
  #+END_COMMENT

* State of the art

* Methodology

* Results
