#+STARTUP: latexpreview
#+STARTUP: indent
#+OPTIONS: toc:nil title:nil

#+LaTeX_CLASS: book
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage{charter}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \graphicspath{{../figures/}}
#+LATEX_HEADER: \usepackage{mathtools}

#+LATEX_HEADER: \providetoggle{images_titlepage}
#+LATEX_HEADER: \settoggle{images_titlepage}{true}

#+BEGIN_COMMENT
Download all needed files for titlepage and convert them.
LaTeX support for svg files sucks.
#+END_COMMENT

#+BEGIN_SRC bash :exports none :results none
  wget https://upload.wikimedia.org/wikipedia/it/5/53/Logo_Universit%C3%A0_Padova.svg \
       -O ../figures/logo_unipd.svg

  inkscape ../figures/logo_unipd.svg --export-pdf=../figures/logo_unipd.pdf

  wget https://upload.wikimedia.org/wikipedia/commons/1/11/RWTH_Logo.svg \
       -O ../figures/logo_rwth.svg

  inkscape ../figures/logo_rwth.svg --export-pdf=../figures/logo_rwth.pdf
#+END_SRC

#+BEGIN_EXPORT latex
\newgeometry{top=1in, bottom=1in, inner=1in, outer=1in}

\begin{titlepage}
  {\Large University of Padova}
  \vspace{5mm}

  {\Large Department of Information Engineering}

  \begin{center}
    \vspace{1cm}
    {\Large \textsl{Master degree in Telecommunication Engineering}} \\
    \vspace{1cm}
    {\scshape\huge TODO: Title}

    \iftoggle{images_titlepage}{
      \vspace{1cm}
      \begin{figure}[h]
        \centering
        \includegraphics[height=5cm]{logo_unipd.pdf}
        \vspace{1cm} \\
        \includegraphics[height=2cm]{logo_rwth.pdf}
        \vspace{1cm}
      \end{figure}
    }

  \end{center}

  \vfill
  \hspace{0.5cm}%
  \renewcommand{\arraystretch}{2.5}
  \begin{tabular}{lr}
    \large \textsl{Author}               & \hspace{5mm} \large Enrico Lovisotto      \\
    \large \textsl{Internal supervisor}  & \hspace{5mm} \large Prof. Andrea Zanella  \\
    \large \textsl{External supervisors} & \hspace{5mm} \large Prof. Petri Mähönen  \\
                                         & \hspace{5mm} \large Dr. Ljiljana Simić   \\
  \end{tabular}
  \vspace{1cm}

  \hfill{\large February 6, 2019} \vspace{3mm}

  \hfill{\Large Academic year 2018-2019 \par}
\end{titlepage}

\restoregeometry
#+END_EXPORT

* Introduction
#+BEGIN_SRC org :exports none
+ background: what are we talking about?
  - SDN => self-optimizing networks
  - flow balancing (TBF)
  - routing adaptation

+ what they do now?
  - summary of state of the art, /basically/

+ shortcomings in current knowledge / solutions
  - limits of SDN over traditional networks: lack of negative results
  - use of abstract topologies ~> this one is obtained through optimization process

+ what are we gonna prove?
  - 99% if the networks are very simple, meant to be more flow aggregators and less clever routers
  - SDN are not inherently good: /probably/ traditional solutions are good in 99% of the networks
  - SDN are relevant when the complexity of the network grows
#+END_SRC
* State of the art

* Methodology
In order to optimize the network, we need a schematic of it => educated guess

** Geographical analysis
#+BEGIN_SRC org :exports none
  OpenStreetMap ~> roads + buildings graph: only methodological consideration

  + cutting NRW maps with Aachen border
  + selecting roads & buildings type
  + ~s2g~ to obtain the graph ~> cite stuff using this approach
    - road polygons to edges
    - intersections as nodes
  + adding building to the graph
    - splitting roads
    - population estimated based on district population, building area
#+END_SRC
** Network design
#+BEGIN_SRC org :exports none
  Using ILP to build the network

  - network requirements
    + ISP recommendations
    + best practices (CISCO, ...)
  - actual solution we are trying to find
    + optimal DSLAM positioning
    + optimal + heuristic check for routers and mainframe positions (restrict root nodes?)

  - why ILP? how does it work? (brief)
  - problem definition
    + idea for the model: Steiner tree + other constraints (cite requirements)
    + actual equations
  - problem complexity: number of variables, constraints (in theory)
#+END_SRC

Previous pre-processing on Aachen city map allowed us to summarize in an undirected graph $G=(V, \,E)$ all relevant information about the streets topology, buildings and estimated number of users.

As specified earlier, each node $i$ is assigned a number of users $u_i$ to serve, which is zero if the node is just a street intersection.
Given that they represent a physical line, edges are given a length value $l_e$, that will be used later to evaluate the access network building cost.

In this chapter we will exploit this information to assess the size of the
** Flow balancing optimization
TODO using machine learning to control TBFs

* Results
** Geographical analysis
+ maps details (whatever): maps only here?
+ graph details
  - number of nodes (building & others)
  - number of edges
  - degree distribution
  - average node distance, population
  - ... anything basically ...

** Network design
ILP results

- CPLEX performance on the problem
  + computational time
  + number of branches
  + (ask Massimo in case)
- show found solution for network
  + analyze performance of found solution (bandwidth, ...)
  + consideration on actual used heuristics

* COMMENT Local variables
# Local Variables:
# eval: (add-hook 'after-save-hook 'org-render-latex-fragments t t)
# End:
